apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    config.kubernetes.io/local-config: "binding"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
